appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: UI7+j2PyvRZSdEVroLwzuwCzCnoK6NNH7Yvifh3aBp1N5oYFN4mp3uFSl5WemhsVZkqHWUUtiRvXv7dt5wuziQXKlLbFZefcR3RcBnqw4BygDr1xFRArnRWs7gUiHYvlLfjQrtivxDK69yqhGf86meSiOqkOoCVuia8oqmdqMPUcTCrNjDJ28ppuvsJGCFWAEPw865y+2FOWWWYGkl4himx3TbePNTx/8F/CQFRBRRxzesGoH3l0JDcHHQeBrUvwGA1wk24JGeIvuuxBuzxwvc5Y8cdzhx5rUH5DcM4baI5L0/FvEqRi2xBXHjFJrTu8vFyYqnVloPNOX33ACoYOv8QBD8Fh2GggfUKieZbTsyRGw/DssOszaUXrdVg/oqpscEx9w5sEIhQ9HObeCVfkv+zuO0X3nxc7doqfAaaLUu7J+1vb3NNpgJHQFqdxXLis/t3Z7UP2HwHpCZG0rHO7Ywd53KXFKWtvzyWOvR0u04/gOKftGBUppqfnQnxYEaav3V1KKkOFZpxuI/h0U+PLjGhGwyyXxLAAqKn5FbKXelq9HHnf1Lc94Ljr7SX4DDu91d/agUW8rIBirjZzNzOPqhA+1ixW9i5tUfvyP25smFi7OaBhpGQZaPuoyjEjJ0pUj9TdJtBvUg/cL9RUz6rF0vVIrMOFwRQzWM0DLrkzJxc=}
