travis:
  secure:
    BINSTAR_TOKEN: Aji3iBjxZD4V78WAfS4/Dl0CiauY/kr+sTxuDVTrmrp+F68f2sMM2drLN0ikh7Ccj68VdtTxH7RuTyk/EqsVixPGGuTSL2a1VaUq9FIRRN0LjLcR8db3GnK7tqVVJZecGWX3Sg3Kwi0TTRAq8BXJnN7yjGP5EzCT3HAlvNmeOayUGDtklmT8SeGQbSHu+mJu8pgVQ9ImixD+LyhOMqNeht//r8eNxQf8Qc/LCiROMVuDcoskfLfhkls2kA7LFTIjq5TyPWEeTEd3LViqF7EuMCHxTf/7mlPXWyY+vfyxKzs6r0vDSgqXCms0SoNQt4tTOFJhVgp9R9nO+aTIUv3tm5zu/BakPtgxxWao6YO0Mx8ZJIAXT8qRaOb3WrI90XHp2TpOxVoJ9I/meRV4kud/pyml27aFnci+LszwrIvDNzGRcPyqOfdMXk1xTGiiPFq11pYnU5DPdosxhi+F0lbylEwPTPYNx8OeQj9JJ+N3qFHz8GqGvltu8G1HC+L597xdMHIeg+/ksqzOQI72bW+spjFHN6uemENuNhPtK6SAW+s4zJFf5dEz01+vn6qy3nAswPOaBq2nrvtQT++uZ1IE5QsjFOufFgY9iaY7NJFyIhOs69Debg9kEW73Z1LSkVIA2TGcVzvOnPtqqYa6cp+lA0OswWKEKKv2g26b0ApT/ns=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
