travis:
  secure:
    BINSTAR_TOKEN: gMQLj6TycNdlqiQmrKmFuqmtAKxI6xQsI+jI6qMGN7GEf8E6y1ncO6kc7xsqzpH8j9lZFOIZhNmSFysNslSg1TorqwI0NR8T8Mrp+++CLdBogpYZsQMRR4K93AIok9wiOKI9Ghp8HveuNwVmUr1PTJz0DzypoQODrgZEjqz4XZrV08QmMQ3vw8NmyEQotye3GAr888a3KjNSSO0OEX/5DcqZ6CEjWlAbfukSJFTtgXSGTYxg4KfoBpjHYvK6QnAHlv5zzuFGWIMeQuymmf6tRrBHnp6DT6BQR3O6d1m2E26e0z5RjmuAt/jaFsZ8yScONj92nUGDRjuwBP9kUTpI9QKnxwfle6LIS7dDdnJjzmZrO7SXPVA24fxVHv4evELIh9rZf8awYFxoEPTgSESFguuoUjizV3Omd9IaUK/prXHguDKT2MR+KFe+uMX9pdgaVa4ScJAiaaw37149jh9Lsy3R6EkzLvTJEkvWo8F7YlTqaxrsIH+Z8zWvLm5KMvSxi1ac3n4Vnmj1uXEFuWo2KTE0KUlDae6V4vgl2pfzlN04tEYfnOGWmiEJdePaJRlU0GwRtSjTLYjP11y+0Ce0Zqq7/jDecUsrOnQLHKSX4I/0Ob8dfP7XzvtDXJIXxMqIFjXZNU1uJI4ypWg9loNGtd713uNRfq6nQLd4vSxVcr8=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
