travis:
  secure:
    BINSTAR_TOKEN: HU4xJoFT2h4fR8KLvPvsSzZopP6CpOy2FJqcJUyrJNoxhaiNAy81cqsQRHmZqc45V878GbqwDgd62fuwbDjeiAZ7z/mh2BLcnGWVljSn0SGOP19ZlNI/vfUe5YbA047NeSx7NNUvZ7uu7wS6hXl4H8L75smglp5ro+D0yj7/4RJvPZTuhgjXgbqKg8l8d/NrhdcfTc8UJwjIVhqqwILdtfB88Oy+7042hapI0VU8A2qaq3988lUlqY+lCtCLUzGsexaWuOQrrtNyOZeXUi8b3pIUOdWBAMqL+lHLXZYnWfE7Sar3SJzlnDmyyy/dbW7V5AkqwzodipkhSowWIq500ulNAyQjWlrXe0+JpI7aRTlrYGHBz05UW8hXTkhQ9HXU8YRTpxwOXDxSFWhxGIPrn3GLyamVlT6oHcRTPdAAmRoU1j0Lxnt+5meNXrpaiW8WZoHkAAFnBEa4A5Usjx+AR2Ma0yXMPy9LCluXHlixOTjvOu5aPl50bG+P04b+uzB7aKQGSt0pW7dYAEjx6uVkuzNyWAGqNjEK6NQGTGsyee7YFbP0fO6wZ8WhGw+O4Y03rZo8A3OQtU6I0fxyBZCVFY1xeNMyY33b6CyJ6Ilk3aQRlYJN4OaOBWXWkNu97l/SsDeMRUh4j92HTm0PRIEGvEKL9RpAw+jCZigWaILEbQE=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
